import type { Metadata } from "next";
import "./globals.css";
import { eudoxusSans, gorditaSans, ibmPlexMono, ubuntu } from "./fonts";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Cryptocurrencies from "@/components/Cryptocurrencies";
import FAQ from "@/components/FAQ";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${eudoxusSans.variable} ${gorditaSans.variable} ${ubuntu.variable} ${ibmPlexMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Cryptocurrencies />
        <FAQ />
        <Footer />
      </body>
    </html>
  );
}
